name: Lighthouse CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing now.sh
        run: yarn add now@16.7.3
      - name: Deploy for staging
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run: >
          npx now deploy
          --local-config=./now.json
          --build-env NODE_ENV=production
          --env NODE_ENV=production
          --public
          --no-clipboard
          --token ${ZEIT_TOKEN}
          > ${HOME}/deployment-url.txt
      - name: Alias with PR number
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run: >
          npx now alias
          --local-config=./now.json
          --token ${ZEIT_TOKEN}
          `cat ${HOME}/deployment-url.txt`
            ${{ github.event.repository.name }}-${{ github.sha }}-lighthouse.now.sh
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            ${{ github.event.repository.name }}-${{ github.sha }}-lighthouse.now.sh/
            ${{ github.event.repository.name }}-${{ github.sha }}-lighthouse.now.sh/?lang=en
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci' # This will save the Lighthouse results as .json files
