name: Lighthouse CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Installing now.sh
        run: yarn add now@16.7.3
        
      - name: Deploy for staging
        env:
          BUILD_ID: ${{ github.sha }}
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run: >
          npx now deploy
          --local-config=./now.json
          --build-env NODE_ENV=production
          --build-env BUILD_ID=${BUILD_ID}
          --env NODE_ENV=production
          --public
          --no-clipboard
          --token ${ZEIT_TOKEN}
      - name: Audit URLs using Lighthouse
        env:
          BUILD_ID: ${ github.sha::8 }
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            ${{ github.event.repository.name }}-${{ BUILD_ID }}-preview.now.sh/
            ${{ github.event.repository.name }}-${{ BUILD_ID }}-preview.now.sh/?lang=en
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci' # This will save the Lighthouse results as .json files
