name: Lighthouse CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing now.sh
        run: yarn add now@16.7.3
      - name: Deploy for staging
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run: >
          npx now deploy
          --local-config=./now.json
          --build-env NODE_ENV=production
          --env NODE_ENV=production
          --public
          --no-clipboard
          --token ${ZEIT_TOKEN}
          > ${HOME}/deployment-url.txt
      - name: Debug output
        run: cat ${HOME}/deployment-url.txt
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            ${{ cat ${HOME}/deployment-url.txt }}
            ${{ cat ${HOME}/deployment-url.txt }}?lang=en
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci' # This will save the Lighthouse results as .json files
